package frc.robot.subsystems.ground_manager;

public enum GroundManagerStates {
    PREPARE_IDLE,
    IDLE,
    PREPARE_INTAKE,
    INTAKE,
    CENTERING,
    BONUS_CENTERING,
    PREPARE_HANDOFF,
    READY_HANDOFF,
    HANDOFF,
    PREPARE_SCORE_L1,
    READY_SCORE_L1,
    SCORE_L1,
    PREPARE_CLIMB,
    CLIMB,
    PREPARE_INVERTED_HANDOFF,
    READY_INVERTED_HANDOFF,
    INVERTED_HANDOFF
}
