package frc.robot.subsystems.armManager;

public enum ArmManagerStates {
    PREPARE_IDLE,
    IDLE,
    PREPARE_INTAKE_GROUND_ALGAE,
    INTAKE_GROUND_ALGAE,
    PREPARE_INTAKE_HIGH_REEF_ALGAE,
    INTAKE_HIGH_REEF_ALGAE,
    PREPARE_INTAKE_LOW_REEF_ALGAE,
    INTAKE_LOW_REEF_ALGAE,
    PREPARE_SCORE_ALGAE_NET,
    WAIT_SCORE_ALGAE_NET,
    SCORE_ALGAE_NET,
    PREPARE_SCORE_ALGAE_PROCESSOR,
    WAIT_SCORE_ALGAE_PROCESSOR,
    SCORE_ALGAE_PROCESSOR,
    PREPARE_SCORE_L4,
    WAIT_L4,
    SCORE_L4,
    PREPARE_HANDOFF_RIGHT,
    WAIT_HANDOFF_RIGHT,
    PREPARE_HANDOFF_MIDDLE,
    WAIT_HANDOFF_MIDDLE,
    PREPARE_HANDOFF_LEFT,
    WAIT_HANDOFF_LEFT,
    ALGAE_LEAVE_REEF,
    CLIMB
}
