package frc.robot.subsystems.armManager;

public enum ArmManagerStates {
    // Idle
    PREPARE_IDLE,
    IDLE,

    // Algae Intake
    PREPARE_INTAKE_GROUND_ALGAE,
    PREPARE_INTAKE_HIGH_REEF_ALGAE,
    PREPARE_INTAKE_LOW_REEF_ALGAE,
    INTAKE_GROUND_ALGAE,
    INTAKE_HIGH_REEF_ALGAE,
    INTAKE_LOW_REEF_ALGAE,
    ALGAE_AWAIT_LEAVE_REEF,

    // Algae Score
    PREPARE_SCORE_ALGAE_NET,
    PREPARE_SCORE_ALGAE_PROCESSOR,
    WAIT_SCORE_ALGAE_NET,
    WAIT_SCORE_ALGAE_PROCESSOR,
    SCORE_ALGAE_NET,
    SCORE_ALGAE_PROCESSOR,

    // Handoff
    PREPARE_HANDOFF_LEFT,
    PREPARE_HANDOFF_MIDDLE,
    PREPARE_HANDOFF_RIGHT,
    PREPARE_HANDOFF_CORAL_MODE,
    WAIT_HANDOFF_LEFT,
    WAIT_HANDOFF_MIDDLE,
    WAIT_HANDOFF_RIGHT,
    WAIT_HANDOFF_CORAL_MODE,

    // Inverted Handoff
    PREPARE_INVERTED_HANDOFF,
    WAIT_INVERTED_HANDOFF,

    // Coral Score
    PREPARE_SCORE_L4,
    PREPARE_SCORE_L3,
    PREPARE_SCORE_L2,
    WAIT_L4,
    WAIT_L3,
    WAIT_L2,
    SCORE_L4,
    SCORE_L3,
    SCORE_L2,

    // Lollipop
    PREPARE_INTAKE_LOLLIPOP,
    INTAKE_LOLLIPOP,

    // Climb
    CLIMB;
}
